logging:
  level:
    com.cqsd.data.mapper: debug
defalt:
  config:
    password: 111111
my:
  login:
    interceptor:
      patterns: /**
      exclude-patterns: /login,/verifyCode
  netty:
    port: 9999